FROM palisade-development

ARG repository="palisade-encrypted-circuit-emulator"
ARG branch=master
ARG tag=master
ARG CC_param=/usr/bin/gcc-10
ARG CXX_param=/usr/bin/g++-10
ARG no_threads=1

ENV DEBIAN_FRONTEND=noninteractive
ENV CC $CC_param
ENV CXX $CXX_param
                                  
#RUN apt-get clean && rm -rf /var/lib/apt/lists/*

#git clone the palisade-development repository and its submodules (this always clones the most latest commit)
RUN git clone https://gitlab.com/palisade/$repository.git 
RUN cd $repository && git checkout $branch && git checkout $tag 
RUN cd $repository && git submodule sync --recursive && git submodule update --init  --recursive

#installing PALISADE and running tests
RUN mkdir /$repository/build 
WORKDIR /$repository/build 
RUN cmake .. && make -j $no_threads
#RUN make install && make testall

