FROM ubuntu:20.04

#install pre-requisites for PALISADE
RUN apt update 
RUN DEBIAN_FRONTEND=noninteractive apt install -y git \ 
        build-essential \
        gcc-10 \
        g++-10 \
        cmake \ 
        autoconf \
        clang-10 \
        libomp5 \
        libomp-dev \
        doxygen \
        graphviz \
        libboost-all-dev=1.71.0.0ubuntu2